const express=require("express")
const uplodeFile = require("../controllers/uplodeFile")
const uplode = require("../middlewares/multer")
const createArchiver = require("../controllers/createArchiver")
const performOCR = require("../controllers/imgToText")
const fileDownlode = require("../controllers/filedownlode")
const autoworkflow = require("../controllers/autoWorkflow")
const getVersionOfFile = require("../controllers/getVersionOfFile")
const imgTotext = require("../controllers/tesseractImgToText")
const totalfiles = require("../controllers/totalFiles")
let router=express.Router()
router.post("/upload",uplode.single("file"),uplodeFile)
router.get("/archiver", createArchiver)
router.get("/imgtotext",uplode.single("file"),performOCR)
router.post("/file",uplode.single("file"),fileDownlode)
router.get("/workflow",autoworkflow)
router.get("/version",getVersionOfFile)
router.get("/tesseract",uplode.single("file"),imgTotext)
router.get("/totalfiles",totalfiles)
module.exports=router
